import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

test("player table does not expose asset-management or director controls", async () => {
  const [html, app, i18n] = await Promise.all([
    readFile("public/index.html", "utf8"),
    readFile("public/app.js", "utf8"),
    readFile("public/i18n.js", "utf8")
  ]);
  const publicSurface = `${html}\n${app}\n${i18n}`;
  const topbarMarkup = html.match(/<div class="topbar-actions">[\s\S]*?<\/div>\s*<\/header>/)?.[0] || "";
  const settingsMarkup = html.match(/<aside class="panel settings-panel[\s\S]*?<aside class="panel log-panel/)?.[0] || "";

  assert.doesNotMatch(publicSurface, /id="assetGrid"|id="assetSearch"|id="assetCategoryFilter"|id="assetShowAll"|id="assetDetail"/);
  assert.doesNotMatch(publicSurface, /asset-library|asset-grid|asset-tools|Asset Library|资产库/);
  assert.doesNotMatch(publicSurface, /data-drawer-open="gm"|data-drawer="gm"|gm-drawer/);
  assert.doesNotMatch(publicSurface, /panel\.director|Director|导演推进/);
  assert.doesNotMatch(publicSurface, /guide\.tab\.evaluation|guide\.eval|Memory Evaluation|记忆评测/);
  assert.doesNotMatch(publicSurface, /admin-panel|admin-drawer|data-admin|后台|管理后台/);
  assert.doesNotMatch(publicSurface, /\/api\/admin|\/api\/assets|\/api\/director/);

  assert.match(html, /data-drawer-open="state"/);
  assert.match(html, /data-drawer-open="character"/);
  assert.match(html, /data-drawer-open="market"/);
  assert.match(html, /data-drawer-open="settings"/);
  assert.match(html, /id="partyStatusBar"/);
  assert.match(html, /id="turnFocus" class="turn-focus"[^>]+data-turn-owner="no-active"[\s\S]*id="turnFocusLabel"[\s\S]*id="turnFocusContext"/);
  assert.match(html, /id="inventoryList"/);
  assert.match(html, /id="marketList"/);
  assert.match(html, /id="playerSummaryDock"/);
  assert.match(html, /id="starterSpellCards"/);
  assert.match(html, /id="dicePanel"/);
  assert.match(html, /name="channel"/);
  assert.match(html, /id="rewardToast"/);
  assert.match(html, /id="actionModeHint"[^>]+data-i18n="action\.hint\.action"/);
  assert.doesNotMatch(topbarMarkup, /id="voiceToggle"|id="voiceSelect"|id="voiceRate"|id="voicePitch"|id="ambienceToggle"|id="ambienceMaster"|id="ambienceMusic"|id="ambienceEnvironment"/);
  assert.doesNotMatch(topbarMarkup, /id="marketButton"|id="tableGuideButton"/);
  assert.match(settingsMarkup, /id="playerMenuSection"[\s\S]*id="marketButton"[\s\S]*id="tableGuideButton"/);
  assert.match(settingsMarkup, /id="voiceToggle"[\s\S]*id="voiceSelect"[\s\S]*id="voiceRate"[\s\S]*id="voicePitch"/);
  assert.match(settingsMarkup, /id="ambienceToggle"[\s\S]*id="ambienceMaster"[\s\S]*id="ambienceMusic"[\s\S]*id="ambienceEnvironment"/);
  assert.doesNotMatch(settingsMarkup, /id="joinForm"|id="speciesSelect"|id="classSelect"|id="starterSpellCards"/);
  assert.match(settingsMarkup, /class="settings-menu settings-section" id="playerMenuSection"[\s\S]*data-i18n="settings\.playerMenuTitle"/);
  assert.match(settingsMarkup, /class="settings-section settings-language-section"[\s\S]*id="languageSelect"/);
  assert.match(settingsMarkup, /class="voice-toolbar settings-section"[\s\S]*class="voice-toolbar-controls"[\s\S]*id="voiceSelect"/);
  assert.match(app, /room\.presentation\?\.sceneAsset/);
  assert.match(app, /entry\.type === "reward"/);
  assert.match(app, /items\/use/);
  assert.match(app, /items\/equip/);
  assert.match(app, /market\/buy/);
  assert.match(app, /market\/sell/);
  assert.match(app, /renderMarketDrawer/);
  assert.match(app, /refreshMarket/);
  assert.match(app, /renderPlayerSummaryDock/);
  assert.match(app, /layerPlayerMenuControls\(\);[\s\S]*bindGuide\(\);[\s\S]*bindDrawers\(\);/);
  assert.match(app, /function layerPlayerMenuControls\(\)[\s\S]*controls\.append\(button\)/);
  assert.match(app, /const hasPlayerBinding = hasLocalPlayerBinding\(\);[\s\S]*const showPlayerSetup = !hasPlayerBinding;/);
  assert.match(app, /function sceneGuidanceSignature\(nextRoom = room\)[\s\S]*nextRoom\.scene\.location[\s\S]*nextRoom\.scene\.objective/);
  assert.match(app, /function renderTurnFocus\(active, localPlayer, hasPlayerBinding, sceneChanged = false\)[\s\S]*els\.turnFocus\.dataset\.turnOwner = owner[\s\S]*els\.actionForm\.dataset\.turnOwner = owner/);
  assert.match(app, /els\.myCharacterButton\.disabled = !hasPlayerBinding/);
  assert.match(app, /els\.marketButton\) els\.marketButton\.disabled = !hasPlayerBinding/);
  assert.match(app, /els\.transcriptPanel\?\.classList\.toggle\("hidden", showPlayerSetup\)/);
  assert.match(app, /const ROOM_SESSION_PREFIX = "aidm\.rooms\."/);
  assert.match(app, /saveRoomPlayerSession\(room\.id, playerId, playerToken\)/);
  assert.match(app, /function restoreRoomPlayerSession\(nextRoom\)[\s\S]*roomPlayerIdKey\(nextRoom\.id\)[\s\S]*roomPlayerTokenKey\(nextRoom\.id\)/);
  assert.match(app, /restoreRoomPlayerSession\(nextRoom\);[\s\S]*room = nextRoom;/);
  assert.match(app, /els\.characterMeta\.textContent = `\$\{localizedSpeciesName\(character\)\} \/ \$\{localizedClassName\(character\)\}`/);
  assert.match(app, /escapeHtml\(localizedSpeciesName\(player\.character\)\)\} \$\{escapeHtml\(localizedClassName\(player\.character\)\)/);
  assert.match(app, /chip\.setAttribute\("aria-label", t\(uiLanguage, "party\.statusAria"/);
  assert.match(app, /class="party-status-subline"[\s\S]*data-party-tag="you"[\s\S]*data-party-tag="active"/);
  assert.match(app, /option\.textContent = voiceProfileOptionLabel\(profile\)/);
  assert.match(app, /option\.title = voiceProfileOptionTitle\(profile\)/);
  assert.match(app, /function localizedVoiceProfileName\(profile\)[\s\S]*主持人旁白/);
  assert.match(app, /function localizedVoiceRoleLabel\(profile\)[\s\S]*角色声线/);
  assert.match(app, /localizeEncounterState\(room\.combat\?\.state \|\| "scouting"\)/);
  assert.match(app, /els\.encounterState\.textContent = localizeEncounterState\(combat\.state \|\| "scouting"\)/);
  assert.match(app, /syncSceneClockLabels\(\)/);
  assert.match(app, /localizeQuestTitle\(quest\)/);
  assert.match(app, /function formatTranscriptTime\(value\)[\s\S]*Intl\.DateTimeFormat\(locale/);
  assert.match(app, /function localeForLanguage\(language\)[\s\S]*"zh-CN"[\s\S]*"en-US"/);
  assert.match(app, /\/memo/);
});

test("v11 production UI controls stay player-scoped", async () => {
  const [html, app, i18n] = await Promise.all([
    readFile("public/index.html", "utf8"),
    readFile("public/app.js", "utf8"),
    readFile("public/i18n.js", "utf8")
  ]);

  assert.match(html, /data-card-select="speciesSelect"[\s\S]*button type="button" class="builder-card active" data-card-value="human"/);
  assert.match(html, /data-card-select="classSelect"[\s\S]*button type="button" class="builder-card active" data-card-value="warrior"/);
  assert.match(html, /class="builder-card-art" src="\/assets\/generated\/options\/aidm-option-01\.png"/);
  assert.match(html, /class="builder-card-art" src="\/assets\/generated\/options\/aidm-option-09\.png"/);
  assert.match(html, /id="starterSpellCards"[^>]+aria-label="Starting spells"/);
  assert.match(html, /id="characterProgressSummary"[\s\S]*id="equipmentSummary"[\s\S]*id="spellList"/);
  assert.match(html, /data-drawer="market"[^>]+aria-hidden="true"[^>]+inert[\s\S]*id="marketWallet"[\s\S]*class="market-note"[\s\S]*id="marketStatus"[\s\S]*id="marketList"/);

  assert.match(app, /function renderStarterSpellCards\(\)[\s\S]*const classId = document\.querySelector\("#classSelect"\)\?\.value \|\| "warrior"/);
  assert.match(app, /const CLASS_RECOMMENDED_ALLOCATIONS = \{[\s\S]*mage: \{ body: 3, agility: 5, mind: 7, presence: 5, spirit: 7 \}/);
  assert.match(app, /function applyRecommendedAttributePreset\(classId\)[\s\S]*CLASS_RECOMMENDED_ALLOCATIONS\[classId\]/);
  assert.match(app, /input\.max = String\(ATTRIBUTE_POINT_BUDGET\.maxSpend\)/);
  assert.match(app, /pointBudget\.ready/);
  assert.match(app, /els\.starterSpellCards\.innerHTML = spells\.map\(\(spell\) => `[\s\S]*<article class="spell-card">/);
  assert.match(app, /const SPELL_ART_FILES = \{[\s\S]*firebolt: "assets\/generated\/spells\/aidm-spell-015-01\.png"[\s\S]*"healing-word": "assets\/generated\/spells\/aidm-spell-015-05\.png"/);
  assert.match(app, /spellArtMarkup\(spell\.id, localizeTextValue\(spell\.label\), "spell-card-art"\)/);
  assert.match(app, /cleric: \[[\s\S]*id: "healing-word"[\s\S]*id: "radiant-bolt"[\s\S]*id: "ward"/);
  assert.doesNotMatch(app, /guarding-strike|shadow-step|silver-tongue|omen-mark|commanding-word|warding-light/);
  assert.match(app, /function renderCharacterProgress\(character\)[\s\S]*els\.characterProgressSummary\.innerHTML = `/);
  assert.match(app, /function renderEquipmentSummary\(inventory, equipmentSummary = null\)[\s\S]*const slots = equipmentSlotSummary\(inventory, equipmentSummary\)/);
  assert.match(app, /function equipmentSlotSummary\(inventory = \[\], equipmentSummary = null\)[\s\S]*slot\.weapon[\s\S]*summarySlot: "mainHand"[\s\S]*slot\.armor[\s\S]*summarySlot: "body"[\s\S]*slot\.focus[\s\S]*slot\.kit/);
  assert.match(app, /function renderMarketDrawer\(\)[\s\S]*const player = getLocalPlayer\(\)/);
  assert.match(app, /if \(nextRoom\.players\?\.some\(\(player\) => player\.id === playerId\)\) \{[\s\S]*saveRoomPlayerSession\(nextRoom\.id, playerId, playerToken\)/);
  assert.match(app, /const storedPlayerId = localStorage\.getItem\(roomPlayerIdKey\(nextRoom\.id\)\) \|\| ""/);
  assert.match(app, /playerId = storedPlayerId;[\s\S]*playerToken = localStorage\.getItem\(roomPlayerTokenKey\(nextRoom\.id\)\) \|\| ""/);
  assert.match(app, /playerId = "";[\s\S]*playerToken = "";/);
  assert.match(app, /const SPECIES_AVATAR_FILES = \{[\s\S]*human: `\$\{AVATAR_OPTION_BASE\}\/aidm-option-01\.png`/);
  assert.match(app, /const CLASS_AVATAR_FILES = \{[\s\S]*warrior: `\$\{AVATAR_OPTION_BASE\}\/aidm-option-09\.png`[\s\S]*envoy: `\$\{AVATAR_OPTION_BASE\}\/aidm-option-16\.png`/);
  assert.match(app, /function avatarDescriptor\(player\)[\s\S]*CLASS_AVATAR_FILES\[classId\][\s\S]*SPECIES_AVATAR_FILES\[speciesId\]/);
  assert.match(app, /data-avatar-kind="\$\{escapeHtml\(descriptor\.kind\)\}"/);
  assert.match(app, /function vitalMeterMarkup\(kind, value, max, label\)[\s\S]*class="vital-meter \$\{escapeHtml\(kind\)\}"/);
  assert.match(app, /class="roster-vitals"[\s\S]*vitalMeterMarkup\("hp", player\.character\.hp[\s\S]*vitalMeterMarkup\("mp", player\.character\.mana/);
  assert.match(app, /class="roster-stat-row"[\s\S]*"vital\.defense"[\s\S]*"vital\.initiative"/);
  assert.match(app, /let diceLandingTimer = null/);
  assert.match(app, /dataset\.rollState = "rolling"[\s\S]*window\.setTimeout\(\(\) => \{[\s\S]*dataset\.rollState = "landed"/);
  assert.match(app, /class="dice-final-score"[\s\S]*dice\.final/);
  assert.match(app, /const margin = diceMarginLabel\(roll\)/);
  assert.match(app, /function diceMarginLabel\(roll = \{\}\)[\s\S]*"dice\.margin\.success"[\s\S]*"dice\.margin\.failure"/);
  assert.match(app, /function hasLocalPlayerBinding\(\)[\s\S]*Boolean\(room && getLocalPlayer\(\) && playerId && playerToken\)/);
  assert.match(app, /els\.actionForm\.dataset\.intent = isChat \? "chat" : "action"/);
  assert.match(app, /const hasPlayerBinding = hasLocalPlayerBinding\(\)/);
  assert.match(app, /modeSelect\.disabled = isChat \|\| !hasPlayerBinding/);
  assert.match(app, /channelSelect\.disabled = !isChat \|\| !hasPlayerBinding/);
  assert.match(app, /textInput\.disabled = !hasPlayerBinding/);
  assert.match(app, /textInput\.placeholder = t\(uiLanguage, hasPlayerBinding \? \(isChat \? "placeholder\.chat" : "placeholder\.action"\) : "action\.noPlayerPlaceholder"\)/);
  assert.match(app, /submitButton\.disabled = !hasPlayerBinding/);
  assert.match(app, /submitButton\.textContent = t\(uiLanguage, hasPlayerBinding \? \(isChat \? "button\.chat" : "button\.act"\) : "action\.noPlayerSubmit"\)/);
  assert.match(app, /els\.actionModeHint\.textContent = t\(uiLanguage, hasPlayerBinding \? \(isChat \? "action\.hint\.chat" : "action\.hint\.action"\) : "action\.noPlayerHint"\)/);
  assert.match(i18n, /"action\.hint\.action": "Action submits a scene move, advances the turn, and may roll dice\."/);
  assert.match(i18n, /"action\.hint\.chat": "Chat posts table talk only; it does not spend a turn or advance the round\."/);
  assert.match(i18n, /"action\.noPlayerHint": "Use the browser that joined this room, or join from setup before acting or chatting\."/);
  assert.match(i18n, /"action\.noPlayerSubmit": "Character required"/);
  assert.match(i18n, /"action\.noPlayerSubmitError": "A local character is required\. Use the browser that joined this room, or join from setup before submitting\."/);
  assert.match(i18n, /"action\.formAria\.noPlayer": "No local character selected\. Use the browser that joined this room, or join from setup before acting or chatting\."/);
  assert.match(app, /const actionText = String\(form\.get\("text"\) \|\| ""\)\.trim\(\)/);
  assert.match(app, /const localPlayer = getLocalPlayer\(\);[\s\S]*if \(!room \|\| !localPlayer \|\| !playerId \|\| !playerToken\) \{[\s\S]*action\.noPlayerSubmitError[\s\S]*syncActionModeControls\(\);[\s\S]*return;/);
  assert.match(app, /error\.chatRequired[\s\S]*error\.actionRequired/);
  assert.match(app, /function syncLocalizedCharacterBuilderOptions\(\)[\s\S]*option\.dataset\.archetypeId = id[\s\S]*option\.value = label/);
  assert.match(app, /showJoinStatus\("join\.nameRequired"\)/);
  assert.match(app, /function showJoinStatus\(key, fallback = ""\)/);
  assert.match(app, /function localizedReplayShareText\(replay\)[\s\S]*replayShareText/);
  assert.match(app, /function ensureSetupGuidance\(\)[\s\S]*setupGuidance[\s\S]*syncSetupGuidance\(\)/);
  assert.match(app, /function syncSetupGuidance\(showSetup = !hasLocalPlayerBinding\(\)\)[\s\S]*setup\.guidance\.playing[\s\S]*setup\.guidance[\s\S]*setup\.ready[\s\S]*setup\.adjustBudget/);
  assert.match(app, /function ensureAudioStatusDock\(\)[\s\S]*audioStatusDockCard[\s\S]*els\.tableStateStrip\.append\(card\)/);
  assert.match(app, /function syncAudioStatusDock\(\)[\s\S]*ambience\.status\.on[\s\S]*data-audio-enabled/);
  assert.match(app, /function transcriptChannel\(entry\)[\s\S]*entry\.visibility\?\.scope === "faction"[\s\S]*return "public"/);
  assert.match(app, /localizedTranscriptAuthor\(entry\)/);
  assert.match(app, /function localizedTranscriptAuthor\(entry = \{\}\)[\s\S]*speaker\.aidm[\s\S]*speaker\.rules[\s\S]*speaker\.table/);
  assert.doesNotMatch(app, /entry\.author \|\| entry\.type\)\} \/ /);
  assert.match(app, /message\.dataset\.channel = channel/);
  assert.match(app, /function channelBadgeMarkup\(channel\)[\s\S]*data-channel-badge="\$\{escapeHtml\(channel\)\}"/);
  assert.match(app, /if \(!player\) \{[\s\S]*market\.joinPrompt/);
  assert.match(app, /function marketPriceLabel\(offer\)[\s\S]*isCurrentCurrencyLabel\(backendLabel\)/);
  assert.match(app, /function marketPurchaseState\(offer, wallet\)[\s\S]*market\.reason\.unavailable[\s\S]*market\.reason\.outOfStock[\s\S]*market\.reason\.insufficientFunds/);
  assert.match(app, /function marketBuyButtonLabel\(definition, reason\)[\s\S]*market\.buyAriaBlocked[\s\S]*market\.buyAria/);
  assert.match(app, /itemArtMarkup\(item, definition, "inventory-item-art"\)/);
  assert.match(app, /itemArtMarkup\(item, definition, "inventory-detail-art"\)/);
  assert.match(app, /itemArtMarkup\(offer, definition, "market-item-art"\)/);
  assert.match(app, /inventory\.rarity/);
  assert.match(app, /function inventoryRarityLabel\(item, definition = inventoryDefinition\(item\)\)[\s\S]*item\?\.rarityLabel \|\| definition\?\.rarityLabel/);
  assert.match(app, /inventory\.sellable/);
  assert.match(app, /inventory\.sellValue/);
  assert.match(app, /function isInventoryItemSellable\(item\)[\s\S]*item\?\.tradeable !== false && item\?\.sellable !== false/);
  assert.match(app, /function inventoryActionState\(item, definition = inventoryDefinition\(item\)\)[\s\S]*inventory\.reason\.toolNarrativeUse[\s\S]*inventory\.reason\.toolNotEquipped/);
  assert.match(app, /class="inventory-action-hints" data-inventory-action-hints/);
  assert.match(app, /function inventoryActionButtonLabel\(action, item, definition, state/);
  assert.match(app, /function itemArtFile\(item, definition = \{\}\)[\s\S]*assetRefFile\(item\?\.definition\?\.assetRef\)[\s\S]*assetRefFile\(item\?\.definitionSnapshot\?\.assetRef\)[\s\S]*assetRefFile\(item\?\.generated\)/);
  assert.match(app, /const ITEM_ART_FILES = \{[\s\S]*longsword: "assets\/generated\/items\/aidm-weapon-cutout-024-01\.png"[\s\S]*"moon-key": "assets\/generated\/items\/aidm-reward-item-006-02\.png"/);
  assert.match(app, /function mappedItemArtFile\(item, definition = \{\}\)[\s\S]*itemCategoryArtKey\(text\)/);
  assert.match(app, /function rewardArtFile\(entry\)[\s\S]*reward\.file[\s\S]*mappedItemArtFile/);
  assert.match(app, /els\.rewardToastImage\.src = assetUrl\(file\)/);
  assert.match(app, /function assetRefFile\(assetRef\)[\s\S]*assetRef\.file[\s\S]*assetRef\.path[\s\S]*assetRef\.image\?\.file/);
  assert.match(app, /function isCurrentEquipmentItem\(item, definition = inventoryDefinition\(item\)\)[\s\S]*equipmentSummary\?\.slots\?\.\[slot\]\?\.item/);
  assert.match(app, /if \(summaryItem\.id && item\?\.id\) return summaryItem\.id === item\.id;/);
  assert.match(app, /summaryItem\.itemId && summaryItem\.itemId === item\?\.itemId && item\?\.equipped/);
  assert.match(app, /data-item-action="equip"/);
  assert.match(app, /selectedInventoryItemId = button\.dataset\.itemId;[\s\S]*renderCharacterDrawer\(\);[\s\S]*revealInventoryDetail\(\);/);
  assert.match(app, /function revealInventoryDetail\(\)[\s\S]*const schedule = window\.requestAnimationFrame \|\| \(\(callback\) => window\.setTimeout\(callback, 0\)\)[\s\S]*\.inventory-detail-card[\s\S]*target\.scrollIntoView\?\.\(\{ behavior: "smooth", block: "start", inline: "nearest" \}\)/);
  assert.match(app, /function revealInventoryFeedback\(\)[\s\S]*const schedule = window\.requestAnimationFrame \|\| \(\(callback\) => window\.setTimeout\(callback, 0\)\)[\s\S]*els\.inventoryStatus\.scrollIntoView\?\.\(\{ behavior: "smooth", block: "start", inline: "nearest" \}\)/);
  assert.match(app, /els\.inventoryStatus\.focus\?\.\(\{ preventScroll: true \}\)/);
  assert.match(app, /setInventoryFeedback\("inventory\.feedback\.sold"/);
  assert.match(app, /setInventoryFeedback\("inventory\.feedback\.equipped"/);
  assert.match(app, /setInventoryFeedback\("inventory\.feedback\.used"/);
  assert.match(app, /function setInventoryFeedback\(key, params = \{\}, kind = "success", fallback = ""\)[\s\S]*if \(inventoryFeedback\) \{[\s\S]*revealInventoryFeedback\(\);[\s\S]*\}/);
  assert.match(app, /const path = action === "sell" \? "market\/sell" : action === "equip" \? "items\/equip" : "items\/use"/);
  assert.match(app, /if \(!button \|\| !room \|\| !selectedInventoryItemId \|\| !hasLocalPlayerBinding\(\)\) return;/);
  assert.match(app, /if \(!room \|\| !hasLocalPlayerBinding\(\)\) return;/);
  assert.match(app, /if \(!button \|\| !room \|\| !hasLocalPlayerBinding\(\)\) return;/);
  assert.match(app, /if \(!room \|\| !hasLocalPlayerBinding\(\) \|\| marketLoading\) return;/);
  assert.match(app, /openRoom\(result\.room\)/);
  assert.match(app, /button type="button" data-market-buy="\$\{escapeHtml\(offer\.itemId\)\}" aria-label="\$\{escapeHtml\(buyLabel\)\}" title="\$\{escapeHtml\(buyLabel\)\}"/);
  assert.match(app, /purchaseState\.reason \? `<span class="market-buy-reason">\$\{escapeHtml\(purchaseState\.reason\)\}<\/span>` : ""/);
  assert.match(app, /function marketOfferActionHint\(offer, definition = marketOfferDefinition\(offer\)\)[\s\S]*market\.card\.toolAfterBuy/);
  assert.match(app, /setMarketFeedback\("market\.feedback\.buying"/);
  assert.match(app, /setMarketFeedback\("market\.feedback\.bought"/);
  assert.match(app, /function setMarketFeedback\(key, params = \{\}, kind = "success", fallback = ""\)[\s\S]*if \(marketFeedback\) \{[\s\S]*revealMarketFeedback\(\);[\s\S]*\}/);
  assert.match(app, /function revealMarketFeedback\(\)[\s\S]*const schedule = window\.requestAnimationFrame \|\| \(\(callback\) => window\.setTimeout\(callback, 0\)\)[\s\S]*els\.marketStatus\.scrollIntoView\?\.\(\{ behavior: "smooth", block: "start", inline: "nearest" \}\)/);
  assert.match(app, /els\.marketStatus\.focus\?\.\(\{ preventScroll: true \}\)/);
  assert.match(app, /api\(`\/api\/rooms\/\$\{room\.id\}\/market\/buy`/);
  assert.match(app, /api\(`\/api\/rooms\/\$\{room\.id\}\/\$\{path\}`/);
  assert.match(i18n, /"market\.reason\.insufficientFunds": "Not enough CR"/);
  assert.match(i18n, /"market\.reason\.outOfStock": "Out of stock"/);
  assert.match(i18n, /"market\.reason\.unavailable": "Unavailable"/);
  assert.match(i18n, /"market\.buyAriaBlocked": "Buy \{item\}: \{reason\}"/);
  assert.match(i18n, /"inventory\.rarity": "Rarity"/);
  assert.match(i18n, /"inventory\.sellable": "Sellable"/);
  assert.match(i18n, /"inventory\.sellValue": "Sell value"/);
  assert.match(i18n, /"inventory\.reason\.toolNarrativeUse": "Tool item: no direct Use button/);
  assert.match(i18n, /"inventory\.feedback\.sold": "Sold \{item\} for \{amount\}\. Wallet: \{wallet\}\. Free-time inventory: no turn spent, no round advanced\."/);
  assert.match(i18n, /"market\.note": "Free-time inventory management for the next scene\. Buying or selling here does not spend a turn or advance the round; use Action for scene moves\."/);
  assert.match(i18n, /"market\.feedback\.buying": "Buying \{item\} as free-time inventory management; turn and round stay unchanged\.\.\."/);
  assert.match(i18n, /"market\.feedback\.bought": "Bought \{item\} for \{price\}\. Wallet: \{wallet\}\. Free-time inventory: no turn spent, no round advanced\./);
  assert.match(i18n, /"ambience\.status\.off": "Off · \{soundscape\}"/);
  assert.match(i18n, /"setup\.guidance": "First seat: \{species\} \{className\}\. \{readiness\} Then join the table\."/);
  assert.match(i18n, /"turnCue\.yourTurn": "Your turn, \{name\}: choose one concrete scene action/);
  assert.match(i18n, /"turnCue\.sceneShifted": "Scene updated"/);
  assert.match(i18n, /"market\.reason\.insufficientFunds": "克朗不足"/);
  assert.match(i18n, /"market\.reason\.outOfStock": "已售罄"/);
  assert.match(i18n, /"market\.reason\.unavailable": "不可购买"/);
  assert.match(i18n, /"inventory\.rarity": "稀有度"/);
  assert.match(i18n, /"inventory\.sellable": "可售卖"/);
  assert.match(i18n, /"inventory\.sellValue": "出售值"/);
  assert.match(i18n, /"inventory\.reason\.toolNarrativeUse": "工具类物品：没有直接使用按钮/);
  assert.match(i18n, /"inventory\.feedback\.sold": "已出售\{item\}，获得 \{amount\}。钱包：\{wallet\}。这是空闲整备：不消耗当前回合，不推进轮次。"/);
  assert.match(i18n, /"market\.note": "下一幕前的空闲整备。这里购买或出售不会消耗当前回合，也不会推进轮次；真正的场景行动请用“行动”。"/);
  assert.match(i18n, /"market\.feedback\.buying": "正在以空闲整备购买\{item\}；不会消耗当前回合，也不会推进轮次\.\.\."/);
  assert.match(i18n, /"market\.feedback\.bought": "已用 \{price\} 购买\{item\}。钱包：\{wallet\}。这是空闲整备：不消耗当前回合，不推进轮次。/);
  assert.match(i18n, /"ambience\.status\.off": "关 · \{soundscape\}"/);
  assert.match(i18n, /"setup\.guidance": "首次入座：\{species\}\{className\}。\{readiness\} 然后加入牌桌。"/);
  assert.match(i18n, /"turnCue\.yourTurn": "轮到你，\{name\}：声明一个具体场景行动/);
  assert.match(i18n, /"turnCue\.sceneShifted": "场景已更新"/);
  assert.match(i18n, /"class\.mage": "法师"/);
  assert.match(i18n, /"voice\.role\.mage": "法师"/);
  assert.match(i18n, /"dice\.rolling": "Rolling"/);
  assert.match(i18n, /"dice\.landed": "Landed"/);
  assert.match(i18n, /"dice\.final": "Final total \{total\}"/);
  assert.match(i18n, /"dice\.margin\.success": "\+\{margin\} over DC"/);
  assert.match(i18n, /"settings\.voiceKicker": "Voice line"/);
  assert.match(i18n, /"archetype\.investigator": "Investigator"/);
  assert.match(i18n, /"join\.nameRequired": "Enter a player name before joining\."/);
  assert.match(i18n, /"replayShareText": "\{title\}: \{players\} players reached round \{round\}\. \{lead\}"/);
  assert.match(i18n, /"dice\.rolling": "掷骰中"/);
  assert.match(i18n, /"dice\.landed": "落定"/);
  assert.match(i18n, /"party\.activeTurn": "当前回合"/);
  assert.match(i18n, /"action\.hint\.action": "行动会提交场景动作，推进回合，并可能掷骰。"/);
  assert.match(i18n, /"action\.noPlayerHint": "请使用已加入本房间的浏览器，或先在设置流程加入角色，再行动或聊天。"/);
  assert.match(i18n, /"action\.noPlayerSubmit": "需要角色"/);
  assert.match(i18n, /"action\.noPlayerSubmitError": "需要本地角色。请使用已加入本房间的浏览器，或先在设置流程加入角色，再提交。"/);
  assert.match(i18n, /"action\.formAria\.noPlayer": "尚未选择本地角色。请使用已加入本房间的浏览器，或先在设置流程加入角色，再行动或聊天。"/);
  assert.match(i18n, /"archetype\.investigator": "调查员"/);
  assert.match(i18n, /"join\.nameRequired": "请先输入玩家名再加入。"/);
  assert.match(i18n, /"replayShareText": "\{title\}：\{players\} 名玩家推进到第 \{round\} 轮。\{lead\}"/);
  assert.match(i18n, /"builder\.frontline": "frontline"/);
  assert.match(i18n, /"builder\.frontline": "前线"/);
  assert.doesNotMatch(app, /data-market-spawn|data-market-edit|data-equipment-admin|data-spell-admin/);
});
