import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

test("static table UI keeps status summary, hidden drawer defaults, and reward toast state hooks", async () => {
  const [html, app, css] = await Promise.all([
    readFile("public/index.html", "utf8"),
    readFile("public/app.js", "utf8"),
    readFile("public/styles.css", "utf8")
  ]);
  const stateDrawerMarkup = html.match(/<aside class="panel state-panel[\s\S]*?<aside class="panel settings-panel/)?.[0] || "";

  assert.match(html, /<section class="table-state-strip"[^>]+aria-label="Current table state"/);
  assert.match(html, /id="turnDock"[\s\S]*id="roundDock"[\s\S]*id="encounterDock"[\s\S]*id="syncDock"[\s\S]*id="playerSummaryDock"/);
  assert.match(html, /id="partyStatusBar"/);
  assert.match(html, /id="playerSetupPanel"[\s\S]*id="joinForm"/);
  assert.match(html, /data-drawer-open="character"/);
  assert.match(html, /data-drawer="character"[^>]+aria-hidden="true"[^>]+inert/);
  assert.match(html, /data-drawer-open="market"/);
  assert.match(html, /data-drawer="market"[^>]+aria-hidden="true"[^>]+inert/);
  assert.match(html, /data-drawer-open="settings"/);
  assert.match(html, /data-drawer="settings"[^>]+aria-hidden="true"[^>]+inert/);
  assert.match(html, /id="inventoryList"[\s\S]*id="inventoryDetail"/);
  assert.match(html, /id="characterProgressSummary"[\s\S]*id="equipmentSummary"[\s\S]*id="spellList"/);
  assert.match(html, /id="marketWallet"[\s\S]*class="market-note"[\s\S]*id="marketStatus"[\s\S]*id="marketList"/);
  assert.doesNotMatch(html.match(/<div class="topbar-actions">[\s\S]*?<\/div>\s*<\/header>/)?.[0] || "", /id="marketButton"|id="tableGuideButton"/);
  assert.match(html, /id="playerMenuSection"[\s\S]*id="marketButton"[\s\S]*id="tableGuideButton"/);
  assert.match(html, /data-card-select="speciesSelect"[\s\S]*data-card-value="human"[\s\S]*data-card-value="elf"[\s\S]*data-card-value="dwarf"[\s\S]*data-card-value="tiefling"/);
  assert.match(html, /data-card-select="classSelect"[\s\S]*data-card-value="warrior"[\s\S]*data-card-value="rogue"[\s\S]*data-card-value="mage"[\s\S]*data-card-value="cleric"/);
  assert.match(html, /class="builder-card-art" src="\/assets\/generated\/options\/aidm-option-01\.png"/);
  assert.match(html, /class="builder-card-art" src="\/assets\/generated\/options\/aidm-option-09\.png"/);
  assert.match(html, /id="starterSpellCards"/);
  assert.match(html, /id="memoForm"[\s\S]*id="memoText"/);
  assert.match(html, /id="dicePanel"[\s\S]*id="dicePanelBody"/);
  assert.match(html, /id="dicePanel" class="dice-panel empty"[^>]+aria-live="polite"[\s\S]*class="dice-roller-animation"[^>]+aria-hidden="true"/);
  assert.match(html, /id="turnFocus" class="turn-focus"[^>]+role="status"[^>]+aria-live="polite"[\s\S]*id="turnFocusLabel"[\s\S]*id="turnFocusContext"/);
  assert.match(html, /<form id="actionForm" class="action-form" data-intent="action"[\s\S]*id="actionModeHint"[^>]+aria-live="polite"/);
  assert.match(html, /name="channel"[\s\S]*value="public"[\s\S]*value="party"/);
  assert.match(html, /class="settings-menu settings-section" id="playerMenuSection"[\s\S]*class="settings-section-head"[\s\S]*id="playerMenuTitle"/);
  assert.match(html, /class="settings-section settings-language-section"[\s\S]*id="languageSelect"/);
  assert.match(html, /class="audio-console settings-section"[\s\S]*id="ambienceMaster"[\s\S]*id="ambienceEnvironment"/);
  assert.match(html, /class="voice-toolbar settings-section"[\s\S]*class="voice-toolbar-controls"[\s\S]*id="voiceRate"[\s\S]*id="voicePitch"/);
  assert.match(html, /id="stateSummary"/);
  assert.match(html, /id="stateChangeList"/);
  assert.match(stateDrawerMarkup, /class="replay-panel"[\s\S]*id="replayButton" type="button"[\s\S]*id="replaySummary" class="replay-summary"/);
  assert.doesNotMatch(stateDrawerMarkup, /id="replayButton"[^>]+disabled/);
  assert.match(app, /renderStateSummary/);
  assert.match(app, /renderPartyStatus/);
  assert.match(app, /renderCharacterDrawer/);
  assert.match(app, /renderMarketDrawer/);
  assert.match(app, /renderPlayerSummaryDock/);
  assert.match(app, /renderDicePanel/);
  assert.match(app, /function renderDicePanel\(\)[\s\S]*delete els\.dicePanel\.dataset\.rollTotal[\s\S]*els\.dicePanel\.dataset\.rollTotal = finalTotalLabel[\s\S]*data-dice-final-score[\s\S]*data-dice-outcome-copy[\s\S]*data-dice-detail/);
  assert.match(app, /function rollEventKey\(entry = \{\}\)[\s\S]*entry\.id[\s\S]*Array\.isArray\(roll\.rolls\)[\s\S]*roll\.expression/);
  assert.match(app, /row\.dataset\.combatResult = result[\s\S]*row\.dataset\.combatAction = entry\.action \|\| ""[\s\S]*row\.innerHTML = combatLogMarkup\(entry\)/);
  assert.match(app, /function combatLogMarkup\(entry = \{\}\)[\s\S]*data-combat-result-copy[\s\S]*data-combat-damage[\s\S]*data-combat-hp-shift/);
  assert.match(app, /function combatLogClasses\(entry = \{\}\)[\s\S]*entry\.critical \? "critical"[\s\S]*combatDamageAmount\(entry\) > 0/);
  assert.match(app, /function combatResult\(entry = \{\}\)[\s\S]*entry\.hit === true[\s\S]*entry\.hit === false/);
  assert.match(app, /bindCharacterDrawer/);
  assert.match(app, /bindBuilderCards/);
  assert.match(app, /bindMarketDrawer/);
  assert.match(app, /layerPlayerMenuControls\(\);[\s\S]*bindGuide\(\);[\s\S]*bindDrawers\(\);/);
  assert.match(app, /function layerPlayerMenuControls\(\)[\s\S]*const menuButtons = \[els\.marketButton, els\.tableGuideButton\]\.filter\(Boolean\)[\s\S]*els\.settingsStack\.prepend\(menu\)[\s\S]*button\.classList\.add\("settings-menu-button"\)[\s\S]*controls\.append\(button\)/);
  assert.match(app, /syncBuilderCards\(group, select\.value\)/);
  assert.match(app, /button\.setAttribute\("aria-pressed", String\(active\)\)/);
  assert.match(app, /els\.replayButton\.addEventListener\("click", async \(\) => \{[\s\S]*aria-busy[\s\S]*dataset\.replayState = "building"[\s\S]*api\(`\/api\/rooms\/\$\{roomId\}\/replay`, \{ timeoutMs: REPLAY_REQUEST_TIMEOUT_MS \}\)[\s\S]*renderReplay\(result\.replay\)/);
  assert.match(app, /function renderReplay\(replay\)[\s\S]*els\.replaySummary\.dataset\.replayState = "built"/);
  assert.match(app, /const SPELL_ART_FILES = \{/);
  assert.match(app, /const ITEM_ART_FILES = \{/);
  assert.match(app, /const ITEM_CATEGORY_ART_FILES = \{/);
  assert.match(app, /spellArtMarkup\(spell\.id, localizeTextValue\(spell\.label\), "spell-card-art"\)/);
  assert.match(app, /function spellArtFile\(spellId\)[\s\S]*SPELL_ART_FILES\[normalized\]/);
  assert.match(app, /renderCharacterProgress\(character\)/);
  assert.match(app, /renderEquipmentSummary\(character\.inventory \|\| \[\], character\.equipmentSummary\)/);
  assert.match(app, /function isEquippableInventoryItem\(item, definition = inventoryDefinition\(item\)\)[\s\S]*Boolean\(item\?\.slot \|\| definition\.slot\)/);
  assert.match(app, /function isCurrentEquipmentItem\(item, definition = inventoryDefinition\(item\)\)[\s\S]*summaryItem[\s\S]*Boolean\(item\?\.equipped\)/);
  assert.match(app, /action === "equip" \? "items\/equip"/);
  assert.match(app, /function marketPriceLabel\(offer\)[\s\S]*t\(uiLanguage, "currency\.cr"\)/);
  assert.match(app, /class="market-card-meta" data-market-card-meta/);
  assert.match(app, /class="inventory-action-hints" data-inventory-action-hints/);
  assert.match(app, /els\.marketStatus\.dataset\.feedbackKind = marketFeedback\?\.kind \|\| ""/);
  assert.match(app, /els\.inventoryStatus\.dataset\.feedbackKind = inventoryFeedback\?\.kind \|\| ""/);
  assert.match(app, /function itemArtMarkup\(item, definition, className\)[\s\S]*itemArtFile\(item, definition\)/);
  assert.match(app, /function itemArtFile\(item, definition = \{\}\)[\s\S]*assetRefFile\(item\?\.assetRef\)[\s\S]*assetRefFile\(item\?\.definitionSnapshot\?\.assetRef\)[\s\S]*assetRefFile\(definition\?\.assetRef\)[\s\S]*assetRefFile\(item\?\.generated\)/);
  assert.match(app, /function mappedItemArtFile\(item, definition = \{\}\)[\s\S]*ITEM_ART_FILES\[itemId\][\s\S]*GENERATED_REWARD_ART_FILES\[itemId\][\s\S]*ITEM_CATEGORY_ART_FILES\[categoryKey\]/);
  assert.match(app, /function rewardArtFile\(entry\)[\s\S]*mappedItemArtFile[\s\S]*ITEM_CATEGORY_ART_FILES\.reward/);
  assert.match(app, /const rewardFile = rewardArtFile\(entry\)/);
  assert.match(app, /function assetRefFile\(assetRef\)[\s\S]*assetRef\.file[\s\S]*assetRef\.url[\s\S]*assetRef\.image\?\.file/);
  assert.match(app, /class="\$\{className\} item-art-fallback"/);
  assert.match(app, /const hasPlayerBinding = hasLocalPlayerBinding\(\);[\s\S]*const showPlayerSetup = !hasPlayerBinding;/);
  assert.match(app, /els\.table\.dataset\.phase = room\.phase \|\| "lobby"/);
  assert.match(app, /els\.table\.classList\.toggle\("in-play", !showPlayerSetup\)/);
  assert.match(app, /els\.table\.classList\.toggle\("setup-open", showPlayerSetup\)/);
  assert.match(app, /const sceneSignature = sceneGuidanceSignature\(room\);[\s\S]*const sceneChanged = Boolean\(lastSceneSignature && sceneSignature && sceneSignature !== lastSceneSignature\)/);
  assert.match(app, /function renderTurnFocus\(active, localPlayer, hasPlayerBinding, sceneChanged = false\)[\s\S]*turnCue\.noLocal[\s\S]*turnCue\.yourTurn[\s\S]*turnCue\.otherTurn/);
  assert.match(app, /function ensureSetupGuidance\(\)[\s\S]*guidance\.id = "setupGuidance"[\s\S]*guidance\.setAttribute\("role", "status"\)[\s\S]*syncSetupGuidance\(\)/);
  assert.match(app, /function syncSetupGuidance\(showSetup = !hasLocalPlayerBinding\(\)\)[\s\S]*setup\.guidance\.playing[\s\S]*setup\.guidance[\s\S]*setup\.ready[\s\S]*setup\.adjustBudget/);
  assert.match(app, /els\.playerSetupPanel\?\.classList\.toggle\("hidden", !showPlayerSetup\)/);
  assert.match(app, /els\.transcriptPanel\?\.classList\.toggle\("hidden", showPlayerSetup\)/);
  assert.match(app, /syncSetupGuidance\(showPlayerSetup\)/);
  assert.match(app, /payload\.channel = form\.get\("channel"\) \|\| "public"/);
  assert.match(app, /submitButton\.textContent = t\(uiLanguage, intent === "chat" \? "button\.sendingChat" : "button\.resolvingAction"\)/);
  assert.match(app, /const ACTION_REQUEST_TIMEOUT_MS = 10000/);
  assert.match(app, /const roomId = room\.id;[\s\S]*const result = await withRealtimePaused\(\(\) => api\(`\/api\/rooms\/\$\{roomId\}\/\$\{path\}`, \{[\s\S]*method: "POST",[\s\S]*timeoutMs: ACTION_REQUEST_TIMEOUT_MS,[\s\S]*body: payload[\s\S]*\}\)\)/);
  assert.match(app, /delete els\.actionForm\.dataset\.submitState/);
  assert.match(app, /function syncActionModeControls\(\)[\s\S]*els\.actionForm\.dataset\.intent = isChat \? "chat" : "action"[\s\S]*els\.actionModeHint\.textContent/);
  assert.match(app, /room\.stateSummary/);
  assert.match(css, /body\.table-active[\s\S]*overflow: hidden/);
  assert.match(css, /\.table[\s\S]*height: calc\(100dvh - 28px\)/);
  assert.match(css, /\.table\.in-play \.player-setup-panel\s*\{[\s\S]*display: none !important/);
  assert.match(css, /\.setup-guidance\s*\{[\s\S]*max-height: 52px;[\s\S]*line-height: 1\.45;[\s\S]*-webkit-line-clamp: 2/);
  assert.match(css, /\.state-summary-grid\s*\{/);
  assert.match(css, /\.party-status-bar\s*\{/);
  assert.match(css, /\.character-drawer/);
  assert.match(css, /\.market-drawer/);
  assert.match(css, /\.settings-drawer/);
  assert.match(css, /\.settings-menu-actions\s*\{[\s\S]*grid-template-columns: repeat\(auto-fit, minmax\(116px, 1fr\)\)/);
  assert.match(css, /\.settings-section-head,[\s\S]*\.voice-toolbar-head\s*\{[\s\S]*display: grid/);
  assert.match(css, /\.voice-toolbar-controls\s*\{[\s\S]*display: flex;[\s\S]*flex-wrap: wrap/);
  assert.match(css, /\.turn-focus\s*\{[\s\S]*grid-row: 2;[\s\S]*min-height: 52px/);
  assert.match(css, /\.turn-focus\[data-turn-owner="local"\]\s*\{[\s\S]*rgba\(61, 155, 148, 0\.18\)/);
  assert.match(css, /\.turn-focus\[data-scene-shifted="true"\] span\s*\{[\s\S]*#ecd28f/);
  assert.match(css, /\.transcript-panel > \.dice-panel\s*\{[\s\S]*grid-row: 4/);
  assert.match(css, /\.transcript-panel > \.transcript\s*\{[\s\S]*grid-row: 5/);
  assert.match(css, /\.transcript-panel > \.action-form\s*\{[\s\S]*grid-row: 6/);
  assert.match(css, /\.inventory-detail-card\s*\{/);
  assert.match(css, /\.inventory-item-art,[\s\S]*\.market-item-art\s*\{[\s\S]*width: 42px;[\s\S]*height: 42px;[\s\S]*object-fit: contain;/);
  assert.match(css, /\.inventory-detail-art\s*\{[\s\S]*width: 64px;[\s\S]*height: 64px;[\s\S]*object-fit: contain;/);
  assert.match(css, /\.inventory-detail,[\s\S]*\.inventory-detail-card\s*\{[\s\S]*scroll-margin-top: 12px/);
  assert.match(css, /\.inventory-action-hints p\s*\{[\s\S]*grid-template-columns: 58px minmax\(0, 1fr\);[\s\S]*min-height: 24px/);
  assert.match(css, /\.inventory-action-hints span\s*\{[\s\S]*display: -webkit-box;[\s\S]*-webkit-line-clamp: 2;[\s\S]*white-space: normal/);
  assert.match(css, /\.inventory-actions button\s*\{[\s\S]*min-width: 0;[\s\S]*font-size: 0\.78rem/);
  assert.match(css, /\.inventory-actions button:disabled\s*\{[\s\S]*border-style: dashed;[\s\S]*background: rgba\(21, 20, 18, 0\.42\)/);
  assert.match(css, /\.item-art-fallback/);
  assert.match(css, /\.market-card\s*\{/);
  assert.match(css, /\.market-note\s*\{[\s\S]*max-height: 36px;[\s\S]*-webkit-line-clamp: 2/);
  assert.match(css, /\.market-card-main > div\s*\{[\s\S]*display: grid;[\s\S]*min-width: 0/);
  assert.match(css, /\.market-card \.market-card-meta\s*\{[\s\S]*grid-template-columns: minmax\(0, 1fr\) auto;[\s\S]*max-height: 18px/);
  assert.match(css, /\.market-card-buy button\s*\{[\s\S]*width: 100%;[\s\S]*min-width: 0/);
  assert.match(css, /\.builder-card\s*\{/);
  assert.match(css, /\.builder-card-art\s*\{/);
  assert.match(css, /\.spell-card\s*\{/);
  assert.match(css, /\.spell-card-art,[\s\S]*\.spell-chip-art\s*\{/);
  assert.match(css, /\.reward-card img,[\s\S]*\.reward-art-fallback\s*\{/);
  assert.match(css, /\.builder-card strong,[\s\S]*\.builder-card small\s*\{[\s\S]*overflow: hidden;[\s\S]*text-overflow: ellipsis;[\s\S]*white-space: nowrap;/);
  assert.match(css, /\.spell-card strong,[\s\S]*\.spell-card small\s*\{[\s\S]*overflow: hidden;[\s\S]*text-overflow: ellipsis;/);
  assert.match(css, /\.market-card strong\s*\{[\s\S]*overflow: hidden;[\s\S]*text-overflow: ellipsis;[\s\S]*white-space: nowrap;/);
  assert.match(css, /\.dice-panel\s*\{/);
  assert.match(css, /#dicePanelBody\s*\{[\s\S]*display: grid;[\s\S]*grid-template-rows: auto auto auto/);
  assert.match(css, /\.dice-panel\[data-roll-state="rolling"\]\s*\{/);
  assert.match(css, /\.dice-final-score\s*\{[\s\S]*text-shadow: 0 1px 0 #000/);
  assert.match(css, /\.dice-detail-line\s*\{[\s\S]*display: flex;[\s\S]*white-space: nowrap/);
  assert.match(css, /\.dice-margin\s*\{[\s\S]*border-radius: 999px/);
  assert.match(css, /--dice-rest-transform/);
  assert.match(css, /@keyframes dice-tumble[\s\S]*var\(--dice-rest-transform\)[\s\S]*var\(--dice-roll-transform\)/);
  assert.match(css, /\.combat-row\.hit\s*\{/);
  assert.match(css, /\.combat-row\.miss\s*\{/);
  assert.match(css, /\.combat-result-pill,[\s\S]*\.combat-damage-pill,[\s\S]*\.combat-hp-shift/);
  assert.match(css, /\.combat-row\.critical \.combat-result-pill,[\s\S]*\.combat-row\.defeated \.combat-result-pill/);
  assert.match(css, /\.action-form\[data-intent="chat"\]\s*\{[\s\S]*rgba\(61, 155, 148, 0\.08\)/);
  assert.match(css, /\.action-mode-hint\s*\{[\s\S]*grid-column: 1 \/ -1;[\s\S]*max-height: 32px;[\s\S]*-webkit-line-clamp: 2;[\s\S]*white-space: normal/);
  assert.match(css, /\.audio-console p\s*\{[\s\S]*-webkit-line-clamp: 2;[\s\S]*overflow-wrap: anywhere/);
  assert.match(css, /\.form-error\s*\{[\s\S]*max-height: 42px;[\s\S]*-webkit-line-clamp: 2/);
  assert.match(css, /#marketStatus\s*\{[\s\S]*position: sticky;[\s\S]*top: 0;[\s\S]*z-index: 2/);
  assert.match(css, /#marketStatus:not\(:empty\)\s*\{[\s\S]*min-height: 42px/);
  assert.match(css, /#marketStatus\[data-feedback-kind="busy"\],[\s\S]*#inventoryStatus\[data-feedback-kind="busy"\]\s*\{[\s\S]*#ecd28f/);
  assert.match(css, /\.party-status-tag\s*\{[\s\S]*text-transform: uppercase/);
  assert.match(app, /turnDock: document\.querySelector\("#turnDock"\)/);
  assert.match(app, /roundDock: document\.querySelector\("#roundDock"\)/);
  assert.match(app, /encounterDock: document\.querySelector\("#encounterDock"\)/);
  assert.match(app, /syncDock: document\.querySelector\("#syncDock"\)/);
  assert.match(app, /els\.turnDock\.textContent = els\.turnBadge\.textContent/);
  assert.match(app, /els\.syncDock\.textContent = t\(uiLanguage, key\)/);
  assert.match(css, /\.table-state-strip\s*\{[\s\S]*grid-template-columns: repeat\(6, minmax\(0, 1fr\)\)/);
  assert.match(css, /\.table-state-strip strong\s*\{[\s\S]*display: block;[\s\S]*max-width: 100%;[\s\S]*text-overflow: ellipsis/);
  assert.match(css, /@media \(max-width: 680px\)[\s\S]*\.inventory-actions\s*\{[\s\S]*grid-template-columns: repeat\(3, minmax\(0, 1fr\)\)/);
  assert.match(css, /@media \(max-width: 680px\)[\s\S]*\.market-card \.market-card-meta\s*\{[\s\S]*grid-template-columns: 1fr;[\s\S]*max-height: 32px/);

  assert.match(html, /data-drawer="party"[^>]+aria-hidden="true"[^>]+inert/);
  assert.match(html, /data-drawer="state"[^>]+aria-hidden="true"[^>]+inert/);
  assert.match(html, /data-drawer="log"[^>]+aria-hidden="true"[^>]+inert/);
  assert.match(html, /data-drawer="market"[^>]+aria-hidden="true"[^>]+inert/);
  assert.match(css, /\.drawer-panel\s*\{[\s\S]*opacity: 0;[\s\S]*pointer-events: none;[\s\S]*visibility: hidden;/);
  assert.match(css, /\.drawer-panel\.open\s*\{[\s\S]*opacity: 1;[\s\S]*pointer-events: auto;[\s\S]*visibility: visible;/);
  assert.match(app, /panel\.classList\.toggle\("open", active\)/);
  assert.match(app, /panel\.inert = !active/);
  assert.match(app, /panel\.inert = true/);

  assert.match(html, /<div class="reward-toast hidden" id="rewardToast"[^>]+aria-hidden="true"/);
  assert.match(app, /shownRewardEventIds/);
  assert.match(app, /els\.rewardToast\.classList\.remove\("hidden"\)/);
  assert.match(app, /els\.rewardToast\.setAttribute\("aria-hidden", "false"\)/);
  assert.match(app, /els\.rewardToast\.classList\.add\("hidden"\)/);
  assert.match(app, /els\.rewardToast\.setAttribute\("aria-hidden", "true"\)/);
  assert.match(app, /function openDrawer\(name, opener = document\.activeElement\)[\s\S]*closeRewardToast\(\);[\s\S]*closeDrawers\(\{ restoreFocus: false \}\)/);
  assert.match(app, /function showRewardToast\(entry\)[\s\S]*document\.body\.classList\.contains\("drawer-open"\)[\s\S]*closeRewardToast\(\);[\s\S]*return;/);
  assert.match(app, /let replayBuildRequestId = 0/);
  assert.match(app, /const REPLAY_REQUEST_TIMEOUT_MS = 10000/);
  assert.match(app, /els\.replayButton\.addEventListener\("click", async \(\) => \{[\s\S]*const requestId = \+\+replayBuildRequestId;[\s\S]*const roomId = room\.id;[\s\S]*closeRewardToast\(\);[\s\S]*dataset\.replayState = "building"[\s\S]*withRealtimePaused\(\(\) => api\(`\/api\/rooms\/\$\{roomId\}\/replay`, \{ timeoutMs: REPLAY_REQUEST_TIMEOUT_MS \}\)\)[\s\S]*renderReplay\(result\.replay\)[\s\S]*dataset\.replayState = "error"/);
  assert.match(app, /function connectEvents\(roomId\)[\s\S]*if \(realtimePauseDepth > 0\)[\s\S]*pendingRealtimeRoomId = roomId[\s\S]*eventSource = new EventSource\(`\/api\/rooms\/\$\{roomId\}\/events`\)[\s\S]*eventSourceGeneration/);
  assert.match(app, /function closeRealtimeSource\(\)[\s\S]*eventSource\.close\(\);[\s\S]*eventSource = null;[\s\S]*eventSourceRoomId = "";[\s\S]*eventSourceGeneration \+= 1;/);
  assert.match(app, /async function withRealtimePaused\(task\)[\s\S]*realtimePauseDepth \+= 1;[\s\S]*closeRealtimeSource\(\);[\s\S]*return await task\(\);[\s\S]*realtimePauseDepth = Math\.max\(0, realtimePauseDepth - 1\);[\s\S]*connectEvents\(nextRoomId\)/);
  assert.match(app, /async function refreshMarket\(\{ clearFeedback = false \} = \{\}\)[\s\S]*const requestId = \+\+marketRefreshRequestId;[\s\S]*withRealtimePaused\(\(\) => api\(`\/api\/rooms\/\$\{roomId\}\/market`, \{ timeoutMs: MARKET_REQUEST_TIMEOUT_MS \}\)\)/);
  assert.match(app, /async function api\(path, options = \{\}\)[\s\S]*AbortController[\s\S]*window\.clearTimeout\(timeout\)/);
  assert.match(css, /\.hidden\s*\{[\s\S]*display: none !important;[\s\S]*\}/);
  assert.match(css, /\.reward-toast\s*\{[\s\S]*position: fixed;[\s\S]*z-index: 34;/);
  assert.match(css, /\.drawer-panel\s*\{[\s\S]*z-index: 28;[\s\S]*pointer-events: none;[\s\S]*visibility: hidden;/);
  assert.match(css, /\.drawer-panel\.open\s*\{[\s\S]*pointer-events: auto;[\s\S]*visibility: visible;/);
  assert.match(css, /\.drawer-scrim\s*\{[\s\S]*z-index: 27;/);
  assert.match(css, /body\.drawer-open \.reward-toast\s*\{[\s\S]*opacity: 0;[\s\S]*pointer-events: none;[\s\S]*visibility: hidden;[\s\S]*display: none !important;/);
  assert.match(css, /@media \(max-width: 680px\)[\s\S]*\.topbar-actions button\s*\{[\s\S]*overflow-wrap: anywhere;[\s\S]*text-overflow: clip;[\s\S]*white-space: normal;/);
});
