import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

test("static table UI keeps status summary, hidden drawer defaults, and reward toast state hooks", async () => {
  const [html, app, css] = await Promise.all([
    readFile("public/index.html", "utf8"),
    readFile("public/app.js", "utf8"),
    readFile("public/styles.css", "utf8")
  ]);

  assert.match(html, /<section class="table-state-strip"[^>]+aria-label="Current table state"/);
  assert.match(html, /id="turnDock"[\s\S]*id="roundDock"[\s\S]*id="encounterDock"[\s\S]*id="syncDock"[\s\S]*id="playerSummaryDock"/);
  assert.match(html, /id="partyStatusBar"/);
  assert.match(html, /id="playerSetupPanel"[\s\S]*id="joinForm"/);
  assert.match(html, /data-drawer-open="character"/);
  assert.match(html, /data-drawer="character"[^>]+aria-hidden="true"[^>]+inert/);
  assert.match(html, /data-drawer-open="market"/);
  assert.match(html, /data-drawer="market"[^>]+aria-hidden="true"[^>]+inert/);
  assert.match(html, /data-drawer-open="settings"/);
  assert.match(html, /data-drawer="settings"[^>]+aria-hidden="true"[^>]+inert/);
  assert.match(html, /id="inventoryList"[\s\S]*id="inventoryDetail"/);
  assert.match(html, /id="characterProgressSummary"[\s\S]*id="equipmentSummary"[\s\S]*id="spellList"/);
  assert.match(html, /id="marketWallet"[\s\S]*id="marketList"[\s\S]*id="marketStatus"/);
  assert.doesNotMatch(html.match(/<div class="topbar-actions">[\s\S]*?<\/div>\s*<\/header>/)?.[0] || "", /id="marketButton"|id="tableGuideButton"/);
  assert.match(html, /id="playerMenuSection"[\s\S]*id="marketButton"[\s\S]*id="tableGuideButton"/);
  assert.match(html, /data-card-select="speciesSelect"[\s\S]*data-card-value="human"[\s\S]*data-card-value="elf"[\s\S]*data-card-value="dwarf"[\s\S]*data-card-value="tiefling"/);
  assert.match(html, /data-card-select="classSelect"[\s\S]*data-card-value="warrior"[\s\S]*data-card-value="rogue"[\s\S]*data-card-value="mage"[\s\S]*data-card-value="cleric"/);
  assert.match(html, /class="builder-card-art" src="\/assets\/generated\/options\/aidm-option-01\.png"/);
  assert.match(html, /class="builder-card-art" src="\/assets\/generated\/options\/aidm-option-09\.png"/);
  assert.match(html, /id="starterSpellCards"/);
  assert.match(html, /id="memoForm"[\s\S]*id="memoText"/);
  assert.match(html, /id="dicePanel"[\s\S]*id="dicePanelBody"/);
  assert.match(html, /name="channel"[\s\S]*value="public"[\s\S]*value="party"/);
  assert.match(html, /id="stateSummary"/);
  assert.match(html, /id="stateChangeList"/);
  assert.match(app, /renderStateSummary/);
  assert.match(app, /renderPartyStatus/);
  assert.match(app, /renderCharacterDrawer/);
  assert.match(app, /renderMarketDrawer/);
  assert.match(app, /renderPlayerSummaryDock/);
  assert.match(app, /renderDicePanel/);
  assert.match(app, /bindCharacterDrawer/);
  assert.match(app, /bindBuilderCards/);
  assert.match(app, /bindMarketDrawer/);
  assert.match(app, /layerPlayerMenuControls\(\);[\s\S]*bindGuide\(\);[\s\S]*bindDrawers\(\);/);
  assert.match(app, /function layerPlayerMenuControls\(\)[\s\S]*const menuButtons = \[els\.marketButton, els\.tableGuideButton\]\.filter\(Boolean\)[\s\S]*els\.settingsStack\.prepend\(menu\)[\s\S]*button\.classList\.add\("settings-menu-button"\)[\s\S]*controls\.append\(button\)/);
  assert.match(app, /syncBuilderCards\(group, select\.value\)/);
  assert.match(app, /button\.setAttribute\("aria-pressed", String\(active\)\)/);
  assert.match(app, /const SPELL_ART_FILES = \{/);
  assert.match(app, /const ITEM_ART_FILES = \{/);
  assert.match(app, /const ITEM_CATEGORY_ART_FILES = \{/);
  assert.match(app, /spellArtMarkup\(spell\.id, localizeTextValue\(spell\.label\), "spell-card-art"\)/);
  assert.match(app, /function spellArtFile\(spellId\)[\s\S]*SPELL_ART_FILES\[normalized\]/);
  assert.match(app, /renderCharacterProgress\(character\)/);
  assert.match(app, /renderEquipmentSummary\(character\.inventory \|\| \[\], character\.equipmentSummary\)/);
  assert.match(app, /function isEquippableInventoryItem\(item, definition = inventoryDefinition\(item\)\)[\s\S]*Boolean\(item\?\.slot \|\| definition\.slot\)/);
  assert.match(app, /function isCurrentEquipmentItem\(item, definition = inventoryDefinition\(item\)\)[\s\S]*summaryItem[\s\S]*Boolean\(item\?\.equipped\)/);
  assert.match(app, /action === "equip" \? "items\/equip"/);
  assert.match(app, /function marketPriceLabel\(offer\)[\s\S]*t\(uiLanguage, "currency\.cr"\)/);
  assert.match(app, /function itemArtMarkup\(item, definition, className\)[\s\S]*itemArtFile\(item, definition\)/);
  assert.match(app, /function itemArtFile\(item, definition = \{\}\)[\s\S]*assetRefFile\(item\?\.assetRef\)[\s\S]*assetRefFile\(item\?\.definitionSnapshot\?\.assetRef\)[\s\S]*assetRefFile\(definition\?\.assetRef\)[\s\S]*assetRefFile\(item\?\.generated\)/);
  assert.match(app, /function mappedItemArtFile\(item, definition = \{\}\)[\s\S]*ITEM_ART_FILES\[itemId\][\s\S]*GENERATED_REWARD_ART_FILES\[itemId\][\s\S]*ITEM_CATEGORY_ART_FILES\[categoryKey\]/);
  assert.match(app, /function rewardArtFile\(entry\)[\s\S]*mappedItemArtFile[\s\S]*ITEM_CATEGORY_ART_FILES\.reward/);
  assert.match(app, /const rewardFile = rewardArtFile\(entry\)/);
  assert.match(app, /function assetRefFile\(assetRef\)[\s\S]*assetRef\.file[\s\S]*assetRef\.url[\s\S]*assetRef\.image\?\.file/);
  assert.match(app, /class="\$\{className\} item-art-fallback"/);
  assert.match(app, /const showPlayerSetup = !localPlayer && room\.phase === "lobby"/);
  assert.match(app, /els\.table\.dataset\.phase = room\.phase \|\| "lobby"/);
  assert.match(app, /els\.table\.classList\.toggle\("in-play", !showPlayerSetup\)/);
  assert.match(app, /els\.table\.classList\.toggle\("setup-open", showPlayerSetup\)/);
  assert.match(app, /els\.playerSetupPanel\?\.classList\.toggle\("hidden", !showPlayerSetup\)/);
  assert.match(app, /els\.transcriptPanel\?\.classList\.toggle\("hidden", showPlayerSetup\)/);
  assert.match(app, /payload\.channel = form\.get\("channel"\) \|\| "public"/);
  assert.match(app, /room\.stateSummary/);
  assert.match(css, /body\.table-active[\s\S]*overflow: hidden/);
  assert.match(css, /\.table[\s\S]*height: calc\(100dvh - 28px\)/);
  assert.match(css, /\.table\.in-play \.player-setup-panel\s*\{[\s\S]*display: none !important/);
  assert.match(css, /\.state-summary-grid\s*\{/);
  assert.match(css, /\.party-status-bar\s*\{/);
  assert.match(css, /\.character-drawer/);
  assert.match(css, /\.market-drawer/);
  assert.match(css, /\.settings-drawer/);
  assert.match(css, /\.settings-menu-actions\s*\{[\s\S]*grid-template-columns: repeat\(auto-fit, minmax\(116px, 1fr\)\)/);
  assert.match(css, /\.inventory-detail-card\s*\{/);
  assert.match(css, /\.inventory-item-art,[\s\S]*\.market-item-art\s*\{[\s\S]*width: 42px;[\s\S]*height: 42px;[\s\S]*object-fit: contain;/);
  assert.match(css, /\.inventory-detail-art\s*\{[\s\S]*width: 64px;[\s\S]*height: 64px;[\s\S]*object-fit: contain;/);
  assert.match(css, /\.item-art-fallback/);
  assert.match(css, /\.market-card\s*\{/);
  assert.match(css, /\.builder-card\s*\{/);
  assert.match(css, /\.builder-card-art\s*\{/);
  assert.match(css, /\.spell-card\s*\{/);
  assert.match(css, /\.spell-card-art,[\s\S]*\.spell-chip-art\s*\{/);
  assert.match(css, /\.reward-card img,[\s\S]*\.reward-art-fallback\s*\{/);
  assert.match(css, /\.builder-card strong,[\s\S]*\.builder-card small\s*\{[\s\S]*overflow: hidden;[\s\S]*text-overflow: ellipsis;[\s\S]*white-space: nowrap;/);
  assert.match(css, /\.spell-card strong,[\s\S]*\.spell-card small\s*\{[\s\S]*overflow: hidden;[\s\S]*text-overflow: ellipsis;/);
  assert.match(css, /\.market-card strong\s*\{[\s\S]*overflow: hidden;[\s\S]*text-overflow: ellipsis;[\s\S]*white-space: nowrap;/);
  assert.match(css, /\.dice-panel\s*\{/);
  assert.match(app, /turnDock: document\.querySelector\("#turnDock"\)/);
  assert.match(app, /roundDock: document\.querySelector\("#roundDock"\)/);
  assert.match(app, /encounterDock: document\.querySelector\("#encounterDock"\)/);
  assert.match(app, /syncDock: document\.querySelector\("#syncDock"\)/);
  assert.match(app, /els\.turnDock\.textContent = els\.turnBadge\.textContent/);
  assert.match(app, /els\.syncDock\.textContent = t\(uiLanguage, key\)/);
  assert.match(css, /\.table-state-strip\s*\{[\s\S]*grid-template-columns: repeat\(5, minmax\(0, 1fr\)\)/);

  assert.match(html, /data-drawer="party"[^>]+aria-hidden="true"[^>]+inert/);
  assert.match(html, /data-drawer="state"[^>]+aria-hidden="true"[^>]+inert/);
  assert.match(html, /data-drawer="log"[^>]+aria-hidden="true"[^>]+inert/);
  assert.match(html, /data-drawer="market"[^>]+aria-hidden="true"[^>]+inert/);
  assert.match(css, /\.drawer-panel\s*\{[\s\S]*opacity: 0;[\s\S]*pointer-events: none;[\s\S]*visibility: hidden;/);
  assert.match(css, /\.drawer-panel\.open\s*\{[\s\S]*opacity: 1;[\s\S]*pointer-events: auto;[\s\S]*visibility: visible;/);
  assert.match(app, /panel\.classList\.toggle\("open", active\)/);
  assert.match(app, /panel\.inert = !active/);
  assert.match(app, /panel\.inert = true/);

  assert.match(html, /<div class="reward-toast hidden" id="rewardToast"[^>]+aria-hidden="true"/);
  assert.match(app, /shownRewardEventIds/);
  assert.match(app, /els\.rewardToast\.classList\.remove\("hidden"\)/);
  assert.match(app, /els\.rewardToast\.setAttribute\("aria-hidden", "false"\)/);
  assert.match(app, /els\.rewardToast\.classList\.add\("hidden"\)/);
  assert.match(app, /els\.rewardToast\.setAttribute\("aria-hidden", "true"\)/);
  assert.match(css, /\.hidden\s*\{[\s\S]*display: none !important;[\s\S]*\}/);
  assert.match(css, /\.reward-toast\s*\{[\s\S]*position: fixed;[\s\S]*z-index: 34;/);
});
